const mongoose = require("mongoose")
const bcrypt = require("bcrypt")
const blocklist = require("./blocklist.json")

const CommentsSchema = new mongoose.Schema({
    value: { type: String, minLength: [3, "comment too short, minimum 3 characters"], maxLength: [500, "comment too long, maximum 500 characters"] },
    date: { type: Date, default: Date.now },
    points: { value: { type: Number, default: 0 }, votedPlus: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }], votedMinus: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }] },
    plate: { type: mongoose.Schema.Types.ObjectId, ref: 'Plate' },
    author: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    visible: { type: Boolean, default: true },
    flagged: { value: { type: Number, default: 0 }, flaggedBy: [{ type: String }] },
    media: {
        links: [],
        image: String,
        video: String
    }
})

const PlateSchema = new mongoose.Schema({
    value: { type: String, unique: true, required: true, minLength: [4, "plate too short, minimum 4 characters"], maxLength: [8, "plate too long, maximum 8 characters"], trim: true, uppercase: true, match: /^[a-zA-Z0-9]+$/ },
    owner: { requestedBy: [{ type: String, default: null }], user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: false, default: null } },
    description: { type: String, maxLength: [300, "too much characters, max 300"], default: null },
    comments: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Comments' }],
    points: { value: { type: Number, default: 0 }, votedPlus: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }], votedMinus: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }] },
    geodata: { country: { type: String, default: null }, region: { type: String, default: null }, flag: { type: String, default: null } },
    views: { value: { type: Number, default: 0 }, viewedBy: [{ type: String }], qrScan: { type: Number, default: 0 } }
})

const UserSchema = new mongoose.Schema({
    username: { type: String, unique: true, trim: true, required: [true, "username is required"], minLength: [3, "username \"{VALUE}\" too short - minimum 3 characters"], maxLength: [69, "username too long, maximum 69 characters"] },
    password: { type: String, required: [true, "password is required"], minLength: [3, "password too short - minimum 3 characters"], maxLength: [64, "password too long, maximum 64 characters"] },
    registerDate: { type: Date, default: Date.now, required: true, immutable: true },
    role: { type: String, enum: ["Admin", "User", "Vip", "Moderator", "Guest"], default: "User" },
    token: { value: { type: String }, device: { type: String }, ip: { type: String }, created: { type: Date, default: Date.now, immutable: true }, modified: { type: Date } },
    owner: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Plate' }],
    comments: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Comments' }],
    reminders: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Plate' }]
})

const ClaimsSchema = new mongoose.Schema({
    plateValue: String,
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    vin: String,
    registerDate: String
})

UserSchema.pre("save", async function (next) {
    var user = this;

    if (!user.isModified('password')) return next();

    if (blocklist.username.some(name => user.username.toLowerCase().includes(name))) return next(new Error("username restricted"));

    // generate a salt
    const salt = await bcrypt.genSalt(10);
    //hash password
    const hashedPassword = await bcrypt.hash(user.password, salt);
    user.password = hashedPassword;
    next();

});

//find geo location of plate by its number
PlateSchema.pre('save', async function (next) {
    //trigger only when value has been changed - meaning creation of new plate
    if (this.isModified('value')) {
        //match plate identifier with country and region
        this.geodata.region = constantsUA[this.value.substring(0, 2).replace(/\d*/gi, "")]
        if (this.geodata.region) { this.geodata.country = "UA"; this.geodata.flag = "🇺🇦" }
        this.geodata.region = constantsPL[this.value.substring(0, 3).replace(/\d*/gi, "")]
        if (this.geodata.region) { this.geodata.country = "PL"; this.geodata.flag = "🇵🇱" }
        next()
    }
    next()
});

//if comment is flagged >X times, hide it
CommentsSchema.pre("updateOne", async function (next) {
    const comment = await this.model.findOne(this.getQuery());
    if (comment && comment.flagged.value > 50) {
        this._update.$set = { ...this._update.$set, visible: false };
    }
    next();
});

//trim comment text & get links
CommentsSchema.pre("save", async function (next) {
    //console.log("pre comment save")
    this.value = this.value.replace(/ {2,}/g, ' ').replace(/\n{3,}/g, '\n\n');
    //links
    const allowedDomains = ["imgur.com", "youtube.com", "youtu.be", "streamable.com"]
    const matches = this.value.match(/(https?:\/\/[^\s]+)/g)
    const links = matches ? Array.from(matches) : null
    if (links) {
        if (links.length > 3) { return next(new Error("too much links, max 3")) }
        const filteredLinks = links.filter(link => allowedDomains.some(domain => link.includes(domain)));
        this.media.links = filteredLinks
    }
    next();
});

//delete all user data
UserSchema.pre('deleteOne', { document: true, query: false }, async function (next) {
    // 'this' is the parent being removed. Provide callbacks here if you want
    // to be notified of the calls' result.
    //console.log("pre delete user")
    await mongoose.model('Comments').deleteMany({ author: this._id });
    await mongoose.model('Plate').updateMany({ 'owner.user': this._id }, { $set: { 'owner.user': null, description: null } });
    await mongoose.model('Claims').deleteMany({ user: this._id });

    next();
});

const User = mongoose.model("User", UserSchema)
const Plate = mongoose.model("Plate", PlateSchema)
const Comments = mongoose.model("Comments", CommentsSchema)
const Claims = mongoose.model("Claims", ClaimsSchema)

module.exports = { User, Plate, Comments, Claims }


const constantsPL = {
    "DJ": "Jelenia Góra",
    "DL": "Legnica",
    "DB": "Wałbrzych",
    "DW": "Wrocław",
    "DX": "Wrocław",
    "DBL": "powiat bolesławiecki (Bolesławiec)",
    "DDZ": "powiat dzierżoniowski (Dzierżoniów)",
    "DGL": "powiat głogowski (Głogów)",
    "DGR": "powiat górowski (Góra)",
    "DJA": "powiat jaworski (Jawor)",
    "DJE": "powiat karkonoski (Jelenia Góra)",
    "DKA": "powiat kamiennogórski (Kamienna Góra)",
    "DKL": "powiat kłodzki (Kłodzko)",
    "DLE": "powiat legnicki (Legnica)",
    "DLB": "powiat lubański (Lubań)",
    "DLU": "powiat lubiński (Lubin)",
    "DLW": "powiat lwówecki (Lwówek Śląski)",
    "DMI": "powiat milicki (Milicz)",
    "DOL": "powiat oleśnicki (Oleśnica)",
    "DOA": "powiat oławski (Oława)",
    "DPL": "powiat polkowicki (Polkowice)",
    "DST": "powiat strzeliński (Strzelin)",
    "DSR": "powiat średzki (Środa Śląska)",
    "DSW": "powiat świdnicki (Świdnica)",
    "DTR": "powiat trzebnicki (Trzebnica)",
    "DBA": "powiat wałbrzyski (Wałbrzych)",
    "DWL": "powiat wołowski (Wołów)",
    "DWR": "powiat wrocławski (Wrocław)",
    "VWR": "powiat wrocławski (Wrocław)",
    "DZA": "powiat ząbkowicki (Ząbkowice Śląskie)",
    "DZG": "powiat zgorzelecki (Zgorzelec)",
    "DZL": "powiat złotoryjski (Złotoryja)",
    "CB": "Bydgoszcz",
    "CG": "Grudziądz",
    "CT": "Toruń",
    "CW": "Włocławek",
    "CAL": "powiat aleksandrowski (Aleksandrów Kujawski)",
    "CBR": "powiat brodnicki (Brodnica)",
    "CBY": "powiat bydgoski (Bydgoszcz)",
    "CCH": "powiat chełmiński (Chełmno)",
    "CGD": "powiat golubsko-dobrzyński (Golub-Dobrzyń)",
    "CGR": "powiat grudziądzki (Grudziądz)",
    "CIN": "powiat inowrocławski (Inowrocław)",
    "CLI": "powiat lipnowski (Lipno)",
    "CMG": "powiat mogileński (Mogilno)",
    "CNA": "powiat nakielski (Nakło nad Notecią)",
    "CRA": "powiat radziejowski (Radziejów)",
    "CRY": "powiat rypiński (Rypin)",
    "CSE": "powiat sępoleński (Sępólno Krajeńskie)",
    "CSW": "powiat świecki (Świecie)",
    "CTR": "powiat toruński (Toruń)",
    "CTU": "powiat tucholski (Tuchola)",
    "CWA": "powiat wąbrzeski (Wąbrzeźno)",
    "CWL": "powiat włocławski (Włocławek)",
    "CZN": "powiat żniński (Żnin)",
    "LB": "Biała Podlaska",
    "LC": "Chełm",
    "LU": "Lublin",
    "LZ": "Zamość",
    "LBI": "powiat bialski (Biała Podlaska)",
    "LBL": "powiat biłgorajski (Biłgoraj)",
    "LCH": "powiat chełmski (Chełm)",
    "LHR": "powiat hrubieszowski (Hrubieszów)",
    "LJA": "powiat janowski (Janów Lubelski)",
    "LKS": "powiat krasnostawski (Krasnystaw)",
    "LKR": "powiat kraśnicki (Kraśnik)",
    "LLB": "powiat lubartowski (Lubartów)",
    "LUB": "powiat lubelski (Lublin)",
    "LLE": "powiat łęczyński (Łęczna)",
    "LLU": "powiat łukowski (Łuków)",
    "LOP": "powiat opolski (Opole Lubelskie)",
    "LPA": "powiat parczewski (Parczew)",
    "LPU": "powiat puławski (Puławy)",
    "LRA": "powiat radzyński (Radzyń Podlaski)",
    "LRY": "powiat rycki (Ryki)",
    "LSW": "powiat świdnicki (Świdnik)",
    "LTM": "powiat tomaszowski (Tomaszów Lubelski)",
    "LWL": "powiat włodawski (Włodawa)",
    "LZA": "powiat zamojski (Zamość)",
    "FG": "Gorzów Wielkopolski",
    "FZ": "Zielona Góra",
    "FGW": "powiat gorzowski (Gorzów Wielkopolski)",
    "FKR": "powiat krośnieński (Krosno Odrzańskie)",
    "FMI": "powiat międzyrzecki (Międzyrzecz)",
    "FNW": "powiat nowosolski (Nowa Sól)",
    "FSL": "powiat słubicki (Słubice)",
    "FSD": "powiat strzelecko-drezdenecki (Strzelce Krajeńskie)",
    "FSU": "powiat sulęciński (Sulęcin)",
    "FSW": "powiat świebodziński (Świebodzin)",
    "FWS": "powiat wschowski (Wschowa)",
    "FZI": "powiat zielonogórski (Zielona Góra)",
    "FZG": "powiat żagański (Żagań)",
    "FZA": "powiat żarski (Żary)",
    "EL": "Łódź",
    "ED": "Łódź",
    "EP": "Piotrków Trybunalski",
    "ES": "Skierniewice",
    "EBE": "powiat bełchatowski (Bełchatów)",
    "EBR": "powiat brzeziński (Brzeziny)",
    "EKU": "powiat kutnowski (Kutno)",
    "ELA": "powiat łaski (Łask)",
    "ELE": "powiat łęczycki (Łęczyca)",
    "ELC": "powiat łowicki (Łowicz)",
    "ELW": "powiat łódzki wschodni (Łódź)",
    "EOP": "powiat opoczyński (Opoczno)",
    "EPA": "powiat pabianicki (Pabianice)",
    "EPJ": "powiat pajęczański (Pajęczno)",
    "EPI": "powiat piotrkowski (Piotrków Trybunalski)",
    "EPD": "powiat poddębicki (Poddębice)",
    "ERA": "powiat radomszczański (Radomsko)",
    "ERW": "powiat rawski (Rawa Mazowiecka)",
    "ESI": "powiat sieradzki (Sieradz)",
    "ESK": "powiat skierniewicki (Skierniewice)",
    "ETM": "powiat tomaszowski (Tomaszów Mazowiecki)",
    "EWI": "powiat wieluński (Wieluń)",
    "EWE": "powiat wieruszowski (Wieruszów)",
    "EZD": "powiat zduńskowolski (Zduńska Wola)",
    "EZG": "powiat zgierski (Zgierz)",
    "KR": "Kraków",
    "KK": "Kraków",
    "KN": "Nowy Sącz",
    "KT": "Tarnów",
    "KBC": "powiat bocheński (Bochnia)",
    "KBA": "powiat bocheński (Bochnia)",
    "KBR": "powiat brzeski (Brzesko)",
    "KCH": "powiat chrzanowski (Chrzanów)",
    "KDA": "powiat dąbrowski (Dąbrowa Tarnowska)",
    "KGR": "powiat gorlicki (Gorlice)",
    "KRA": "powiat krakowski (Kraków)",
    "KLI": "powiat limanowski (Limanowa)",
    "KMI": "powiat miechowski (Miechów)",
    "KMY": "powiat myślenicki (Myślenice)",
    "KNS": "powiat nowosądecki (Nowy Sącz)",
    "KNT": "powiat nowotarski (Nowy Targ)",
    "KOL": "powiat olkuski (Olkusz)",
    "KOS": "powiat oświęcimski (Oświęcim)",
    "KPR": "powiat proszowicki (Proszowice)",
    "KSU": "powiat suski (Sucha Beskidzka)",
    "KTA": "powiat tarnowski (Tarnów)",
    "KTT": "powiat tatrzański (Zakopane)",
    "KWA": "powiat wadowicki (Wadowice)",
    "KWI": "powiat wielicki (Wieliczka)",
    "WB": "Warszawa Bemowo",
    "WA": "Warszawa Białołęka",
    "WD": "Warszawa Bielany",
    "WE": "Warszawa Mokotów",
    "WU": "Warszawa Ochota",
    "WF": "Warszawa Praga-Południe",
    "WH": "Warszawa Praga-Północ",
    "WW": "Warszawa",
    "WI": "Warszawa Śródmieście",
    "WJ": "Warszawa Targówek",
    "WK": "Warszawa Ursus",
    "WN": "Warszawa Ursynów",
    "WT": "Warszawa Wawer",
    "WY": "Warszawa Wola",
    "WX": "Warszawa Żoliborz",
    "WO": "Ostrołęka",
    "WP": "Płock",
    "WR": "Radom",
    "WS": "Siedlce",
    "WBR": "powiat białobrzeski (Białobrzegi)",
    "WCI": "powiat ciechanowski (Ciechanów)",
    "WG": "powiat garwoliński (Garwolin)",
    "WGS": "powiat gostyniński (Gostynin)",
    "WGM": "powiat grodziski (Grodzisk Mazowiecki)",
    "WGR": "powiat grójecki (Grójec)",
    "WKZ": "powiat kozienicki (Kozienice)",
    "WL": "powiat legionowski (Legionowo)",
    "WLI": "powiat lipski (Lipsko)",
    "WLS": "powiat łosicki (Łosice)",
    "WMA": "powiat makowski (Maków Mazowiecki)",
    "WM": "powiat miński (Mińsk Mazowiecki)",
    "WML": "powiat mławski (Mława)",
    "WND": "powiat nowodworski (Nowy Dwór Mazowiecki)",
    "WOS": "powiat ostrołęcki (Ostrołęka)",
    "WOR": "powiat ostrowski (Ostrów Mazowiecka)",
    "WOT": "powiat otwocki (Otwock)",
    "WPI": "powiat piaseczyński (Piaseczno)",
    "WPA": "powiat piaseczyński (Piaseczno)",
    "WPL": "powiat płocki (Płock)",
    "WPN": "powiat płoński (Płońsk)",
    "WPR": "powiat pruszkowski (Pruszków)",
    "WPP": "powiat pruszkowski (Pruszków)",
    "WPS": "powiat pruszkowski (Pruszków)",
    "WPZ": "powiat przasnyski (Przasnysz)",
    "WPY": "powiat przysuski (Przysucha)",
    "WPU": "powiat pułtuski (Pułtusk)",
    "WRA": "powiat radomski (Radom)",
    "WSI": "powiat siedlecki (Siedlce)",
    "WSE": "powiat sierpecki (Sierpc)",
    "WSC": "powiat sochaczewski (Sochaczew)",
    "WSK": "powiat sokołowski (Sokołów Podlaski)",
    "WSZ": "powiat szydłowiecki (Szydłowiec)",
    "WZ": "powiat warszawski zachodni (Ożarów Mazowiecki)",
    "WWE": "powiat węgrowski (Węgrów)",
    "WWL": "powiat wołomiński (Wołomin)",
    "WV": "powiat wołomiński (Wołomin)",
    "WWY": "powiat wyszkowski (Wyszków)",
    "WZW": "powiat zwoleński (Zwoleń)",
    "WZU": "powiat żuromiński (Żuromin)",
    "WZY": "powiat żyrardowski (Żyrardów)",
    "OP": "Opole",
    "OB": "powiat brzeski (Brzeg)",
    "OGL": "powiat głubczycki (Głubczyce)",
    "OK": "powiat kędzierzyńsko-kozielski (Kędzierzyn-Koźle)",
    "OKL": "powiat kluczborski (Kluczbork)",
    "OKR": "powiat krapkowicki (Krapkowice)",
    "ONA": "powiat namysłowski (Namysłów)",
    "ONY": "powiat nyski (Nysa)",
    "OOL": "powiat oleski (Olesno)",
    "OPO": "powiat opolski (Opole)",
    "OPR": "powiat prudnicki (Prudnik)",
    "OST": "powiat strzelecki (Strzelce Opolskie)",
    "RK": "Krosno",
    "RP": "Przemyśl",
    "RZ": "Rzeszów",
    "RT": "Tarnobrzeg",
    "RBI": "powiat bieszczadzki (Ustrzyki Dolne)",
    "RBR": "powiat brzozowski (Brzozów)",
    "RDE": "powiat dębicki (Dębica)",
    "RJA": "powiat jarosławski (Jarosław)",
    "RJS": "powiat jasielski (Jasło)",
    "RKL": "powiat kolbuszowski (Kolbuszowa)",
    "RKR": "powiat krośnieński (Krosno)",
    "RLS": "powiat leski (Lesko)",
    "RLE": "powiat leżajski (Leżajsk)",
    "RLU": "powiat lubaczowski (Lubaczów)",
    "RLA": "powiat łańcucki (Łańcut)",
    "RMI": "powiat mielecki (Mielec)",
    "RNI": "powiat niżański (Nisko)",
    "RPR": "powiat przemyski (Przemyśl)",
    "RPZ": "powiat przeworski (Przeworsk)",
    "RRS": "powiat ropczycko-sędziszowski (Ropczyce)",
    "RZE": "powiat rzeszowski (Rzeszów)",
    "RSA": "powiat sanocki (Sanok)",
    "RST": "powiat stalowowolski (Stalowa Wola)",
    "RSR": "powiat strzyżowski (Strzyżów)",
    "RTA": "powiat tarnobrzeski (Tarnobrzeg)",
    "BI": "Białystok",
    "BL": "Łomża",
    "BS": "Suwałki",
    "BAU": "powiat augustowski (Augustów)",
    "BIA": "powiat białostocki (Białystok)",
    "BBI": "powiat bielski (Bielsk Podlaski)",
    "BGR": "powiat grajewski (Grajewo)",
    "BHA": "powiat hajnowski (Hajnówka)",
    "BKL": "powiat kolneński (Kolno)",
    "BLM": "powiat łomżyński (Łomża)",
    "BMN": "powiat moniecki (Mońki)",
    "BSE": "powiat sejneński (Sejny)",
    "BSI": "powiat siemiatycki (Siemiatycze)",
    "BSK": "powiat sokólski (Sokółka)",
    "BSU": "powiat suwalski (Suwałki)",
    "BWM": "powiat wysokomazowiecki (Wysokie Mazowieckie)",
    "BZA": "powiat zambrowski (Zambrów)",
    "GD": "Gdańsk",
    "XD": "Gdańsk",
    "GA": "Gdynia",
    "GS": "Słupsk",
    "GSP": "Sopot",
    "GBY": "powiat bytowski (Bytów)",
    "GCH": "powiat chojnicki (Chojnice)",
    "GCZ": "powiat człuchowski (Człuchów)",
    "GDA": "powiat gdański (Pruszcz Gdański)",
    "GKA": "powiat kartuski (Kartuzy)",
    "GKY": "powiat kartuski (Kartuzy) - dla pojazdów zabytkowych",
    "GKS": "powiat kościerski (Kościerzyna)",
    "GKW": "powiat kwidzyński (Kwidzyn)",
    "GLE": "powiat lęborski (Lębork)",
    "GMB": "powiat malborski (Malbork)",
    "GND": "powiat nowodworski (Nowy Dwór Gdański)",
    "GPU": "powiat pucki (Puck)",
    "GSL": "powiat słupski (Słupsk)",
    "GST": "powiat starogardzki (Starogard Gdański)",
    "GSZ": "powiat sztumski (Sztum)",
    "GTC": "powiat tczewski (Tczew)",
    "GWE": "powiat wejherowski (Wejherowo)",
    "GWO": "powiat wejherowski (Wejherowo)",
    "SB": "Bielsko-Biała",
    "SY": "Bytom",
    "SH": "Chorzów",
    "SC": "Częstochowa",
    "SD": "Dąbrowa Górnicza",
    "SG": "Gliwice",
    "SJZ": "Jastrzębie-Zdrój",
    "SJ": "Jaworzno",
    "SK": "Katowice",
    "SM": "Mysłowice",
    "SPI": "Piekary Śląskie",
    "SL": "Ruda Śląska",
    "SRS": "Ruda Śląska",
    "SR": "Rybnik",
    "SI": "Siemianowice Śląskie",
    "SO": "Sosnowiec",
    "SW": "Świętochłowice",
    "ST": "Tychy",
    "SZ": "Zabrze",
    "SZO": "Żory",
    "SBE": "powiat będziński (Będzin)",
    "SBI": "powiat bielski (Bielsko-Biała)",
    "SBL": "powiat bieruńsko-lędziński (Bieruń)",
    "STY": "powiat tyski (Tychy)",
    "SCI": "powiat cieszyński (Cieszyn)",
    "SCN": "powiat cieszyński (Cieszyn)",
    "SCZ": "powiat częstochowski (Częstochowa)",
    "SGL": "powiat gliwicki (Gliwice)",
    "SKL": "powiat kłobucki (Kłobuck)",
    "SLU": "powiat lubliniecki (Lubliniec)",
    "SMI": "powiat mikołowski (Mikołów)",
    "SMY": "powiat myszkowski (Myszków)",
    "SPS": "powiat pszczyński (Pszczyna)",
    "SRC": "powiat raciborski (Racibórz)",
    "SRB": "powiat rybnicki (Rybnik)",
    "STA": "powiat tarnogórski (Tarnowskie Góry)",
    "SWD": "powiat wodzisławski (Wodzisław Śląski)",
    "SWZ": "powiat wodzisławski (Wodzisław Śląski)",
    "SZA": "powiat zawierciański (Zawiercie)",
    "SZY": "powiat żywiecki (Żywiec)",
    "TK": "Kielce",
    "TBU": "powiat buski (Busko Zdrój)",
    "TJE": "powiat jędrzejowski (Jędrzejów)",
    "TKA": "powiat kazimierski (Kazimierza Wielka)",
    "TKI": "powiat kielecki (Kielce)",
    "TKN": "powiat konecki (Końskie)",
    "TOP": "powiat opatowski (Opatów)",
    "TOS": "powiat ostrowiecki (Ostrowiec Świętokrzyski)",
    "TPI": "powiat pińczowski (Pińczów)",
    "TSA": "powiat sandomierski (Sandomierz)",
    "TSK": "powiat skarżyski (Skarżysko-Kamienna)",
    "TST": "powiat starachowicki (Starachowice)",
    "TSZ": "powiat staszowski (Staszów)",
    "TLW": "powiat włoszczowski (Włoszczowa)",
    "NE": "Elbląg",
    "NO": "Olsztyn",
    "NBA": "powiat bartoszycki (Bartoszyce)",
    "NBR": "powiat braniewski (Braniewo)",
    "NDZ": "powiat działdowski (Działdowo)",
    "NEB": "powiat elbląski (Elbląg)",
    "NEL": "powiat ełcki (Ełk)",
    "NGI": "powiat giżycki (Giżycko)",
    "NGO": "powiat gołdapski (Gołdap)",
    "NOG": "powiat olecko-gołdapski (Olecko)",
    "NIL": "powiat iławski (Iława)",
    "NKE": "powiat kętrzyński (Kętrzyn)",
    "NLI": "powiat lidzbarski (Lidzbark Warmiński)",
    "NMR": "powiat mrągowski (Mrągowo)",
    "NNI": "powiat nidzicki (Nidzica)",
    "NNM": "powiat nowomiejski (Nowe Miasto Lubawskie)",
    "NOE": "powiat olecki (Olecko)",
    "NOL": "powiat olsztyński (Olsztyn)",
    "NOS": "powiat ostródzki (Ostróda)",
    "NPI": "powiat piski (Pisz)",
    "NSZ": "powiat szczycieński (Szczytno)",
    "NWE": "powiat węgorzewski (Węgorzewo)",
    "PK": "Kalisz",
    "PA": "Kalisz",
    "PN": "Konin",
    "PKO": "Konin",
    "PL": "Leszno",
    "PO": "Poznań",
    "PY": "Poznań",
    "PCH": "powiat chodzieski (Chodzież)",
    "PCT": "powiat czarnkowsko-trzcianecki (Czarnków)",
    "PGN": "powiat gnieźnieński (Gniezno)",
    "PGS": "powiat gostyński (Gostyń)",
    "PGO": "powiat grodziski (Grodzisk Wielkopolski)",
    "PJA": "powiat jarociński (Jarocin)",
    "PKA": "powiat kaliski (Kalisz)",
    "PKE": "powiat kępiński (Kępno)",
    "PKL": "powiat kolski (Koło)",
    "PKN": "powiat koniński (Konin)",
    "PKS": "powiat kościański (Kościan)",
    "PKR": "powiat krotoszyński (Krotoszyn)",
    "PLE": "powiat leszczyński (Leszno)",
    "PMI": "powiat międzychodzki (Międzychód)",
    "PNT": "powiat nowotomyski (Nowy Tomyśl)",
    "POB": "powiat obornicki (Oborniki)",
    "POS": "powiat ostrowski (Ostrów Wielkopolski)",
    "POT": "powiat ostrzeszowski (Ostrzeszów)",
    "PP": "powiat pilski (Piła)",
    "PPL": "powiat pleszewski (Pleszew)",
    "PZ": "powiat poznański (Poznań)",
    "POZ": "powiat poznański (Poznań)",
    "PRA": "powiat rawicki (Rawicz)",
    "PSL": "powiat słupecki (Słupca)",
    "PSZ": "powiat szamotulski (Szamotuły)",
    "PSE": "powiat śremski (Śrem)",
    "PSR": "powiat średzki (Środa Wielkopolska)",
    "PTU": "powiat turecki (Turek)",
    "PWA": "powiat wągrowiecki (Wągrowiec)",
    "PWL": "powiat wolsztyński (Wolsztyn)",
    "PWR": "powiat wrzesiński (Września)",
    "PZL": "powiat złotowski (Złotów)",
    "ZK": "Koszalin",
    "ZS": "Szczecin",
    "ZZ": "Szczecin",
    "ZSW": "Świnoujście",
    "ZBI": "powiat białogardzki (Białogard)",
    "ZCH": "powiat choszczeński (Choszczno)",
    "ZDR": "powiat drawski (Drawsko Pomorskie)",
    "ZGL": "powiat goleniowski (Goleniów)",
    "ZGY": "powiat gryficki (Gryfice)",
    "ZGR": "powiat gryfiński (Gryfino)",
    "ZKA": "powiat kamieński (Kamień Pomorski)",
    "ZKL": "powiat kołobrzeski (Kołobrzeg)",
    "ZKO": "powiat koszaliński (Koszalin)",
    "ZLO": "powiat łobeski (Łobez) (od 1 stycznia 2002)",
    "ZMY": "powiat myśliborski (Myślibórz)",
    "ZPL": "powiat policki (Police)",
    "ZPY": "powiat pyrzycki (Pyrzyce)",
    "ZSL": "powiat sławieński (Sławno)",
    "ZST": "powiat stargardzki (Stargard)",
    "ZSZ": "powiat szczecinecki (Szczecinek)",
    "ZSD": "powiat świdwiński (Świdwin)",
    "ZWA": "powiat wałecki (Wałcz)",
}

const constantsUA = {
    "AX": "obwód charkowski",
    "KX": "obwód charkowski",
    "BT": "obwód chersoński",
    "HT": "obwód chersoński",
    "BX": "obwód chmielnicki",
    "HX": "obwód chmielnicki",
    "CA": "obwód czerkaski",
    "IA": "obwód czerkaski",
    "CB": "obwód czernihowski",
    "IB": "obwód czernihowski",
    "CE": "obwód czerniowiecki",
    "IE": "obwód czerniowiecki",
    "AE": "obwód dniepropetrowski",
    "KE": "obwód dniepropetrowski",
    "AH": "obwód doniecki",
    "KH": "obwód doniecki",
    "AT": "obwód iwanofrankowski",
    "KT": "obwód iwanofrankowski",
    "AI": "obwód kijowski",
    "KI": "obwód kijowski",
    "AA": "miasto Kijów",
    "KA": "miasto Kijów",
    "BA": "obwód kirowohradzki",
    "NA": "obwód kirowohradzki",
    "BC": "obwód lwowski",
    "HC": "obwód lwowski",
    "BB": "obwód ługański",
    "HB": "obwód ługański",
    "BE": "obwód mikołajowski",
    "HE": "obwód mikołajowski",
    "BH": "obwód odeski",
    "HH": "obwód odeski",
    "BI": "obwód połtawski",
    "HI": "obwód połtawski",
    "AK": "Republika Autonomiczna Krymu",
    "KK": "Republika Autonomiczna Krymu",
    "BK": "obwód rówieński",
    "HK": "obwód rówieński",
    "CH": "miasto Sewastopol",
    "IH": "miasto Sewastopol",
    "BM": "obwód sumski",
    "HM": "obwód sumski",
    "BO": "obwód tarnopolski",
    "HO": "obwód tarnopolski",
    "AB": "obwód winnicki",
    "KB": "obwód winnicki",
    "AC": "obwód wołyński",
    "KC": "obwód wołyński",
    "AO": "obwód zakarpacki",
    "KO": "obwód zakarpacki",
    "AP": "obwód zaporoski",
    "KP": "obwód zaporoski",
    "AM": "obwód żytomierski",
    "KM": "obwód żytomierski",
    "II": "pojazdy państwowe",
}